version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"              # requirements.txt のあるディレクトリ
    schedule:
      interval: "weekly"         # daily/weekly/monthly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
